### ISSUE TITLE
Screenshots? Forum thread?

### ISSUE THREAD

**Issue by int-ua** [pixel-32/CDDA-tileset#50]
I guess it is not ready yet, but still, is there a place it's discussed? I've been helping a bit with UltiCa lately, maybe you would like to try using Blender for something? I've made some templates. They are far from ideal, but can help with unifying lighting angles, producing different rotations of same object.

**Comment by John-Candlebury** [comment]
Theres a handfull of milestones I want to pass before making a big public announcement about the tileset.

But I might be interested in looking into your blender templates however.

**Comment by int-ua** [comment]
https://github.com/int-ua/blender-pixelart
Tell me if you have any questions about these or Blender in general :)
